kind: ApplicationSet
apiVersion: argoproj.io/v1alpha1
metadata:
  name: kratix
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            cluster-type: platform
        values:
          cluster-type: platform
#    - clusters:
#        selector:
#          matchLabels:
#            cluster-type: worker
#        values:
#          cluster-type: worker
  template:
    metadata:
      name: "kratix-{{values.cluster-type}}"
      namespace: argocd
    spec:
      destination:
        namespace: "kratix-{{values.cluster-type}}-system"
        server: https://kubernetes.default.svc
      project: core-services
      source:
        path: "gitops-repo/kratix-{{values.cluster-type}}"
        repoURL: https://github.com/kzap/platform-demo.git
      syncPolicy:
        automated: {}
        syncOptions: # Sync options which modifies sync behavior
          - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
