apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-tls-certs-cm
data:
  0.0.0.0: |
    -----BEGIN CERTIFICATE-----
    MIIDczCCAlugAwIBAgIQRWIhuDNxiuif0qo61EEefDANBgkqhkiG9w0BAQsFADAi
    MRAwDgYDVQQKEwdBY21lIENvMQ4wDAYDVQQDEwVHaXRlYTAeFw0yMjEyMDgxNzE1
    MDFaFw0yMzEyMDgxNzE1MDFaMCIxEDAOBgNVBAoTB0FjbWUgQ28xDjAMBgNVBAMT
    BUdpdGVhMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvlcKmLpfI6te
    IGIeVwjijSwY8PefL7l6xHHUFEKcgBmpaHWv/GHlI9XONDw6AlOGtg4oTeRs3jiv
    ooLCYM5udOQcfKo7BXGVByoVPX2mv8dA4EboFuneqaVvOMpPwoRK5kvbAtnk9h0K
    T2nSfPujZU6yHMNA0EHPUvBlJmNGxc5oVHQW8Y+RkgLI9VAzLp8bhgTS1ATlVC/Y
    PQ+qp6hsLRa+LlNTKQxBRAal751Q+9U136bDf83P37tx2Azx47NfXXDijijX6ggd
    ScGlSl/cgPjcQyvXL0PAD23pE67d371iEDHNEK4CRPxyMV7lZvYw2y9np/jVF1Zn
    1EsKOLcy0wIDAQABo4GkMIGhMA4GA1UdDwEB/wQEAwICpDATBgNVHSUEDDAKBggr
    BgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRiRYVn6dg4g7ib8INU
    srD4nIDjpjBKBgNVHREEQzBBgglsb2NhbGhvc3SCImdpdGVhLWh0dHAuZ2l0ZWEu
    c3ZjLmNsdXN0ZXIubG9jYWyHBKwSAAKHBKwSAAOHBKwSAAQwDQYJKoZIhvcNAQEL
    BQADggEBABXv5SgXORK8S0LNsiCu0of85jGf2sIF3HrePPG0wJ6+6klRdNfc1q8p
    xMU449Rtiu376wEiVWQKTxDqPYhs9FUB82B5zSz/hvaPcp0pdyGwRYsZcrhJIP4l
    jePhm7DKJxif/qgF/SUVoeyM6JBPYDKtEX6OY9Fqz8YGBzTs6SPbcy0R2GNzKUPN
    GHLJeYaQyftti1K5OcOOiHFbugSx9MPiwzjiz4PMrhqX4Z2KzBR8HopyV9SZlCjk
    I6baRxx9L+2XUCHjUJmQsJK/qyqsQAycvA0uuVoIAu76V82SLVhgTF8PviSgDvqg
    xC1mgd32vVqezjjM1QnLFGXc62HqNF0=
    -----END CERTIFICATE-----