kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: worker
#containerdConfigPatches:
#- |-
#  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
#    endpoint = ["http://kind-registry:5000"]
nodes:
- role: control-plane
  image: kindest/node:v1.22.15
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 9080
    protocol: TCP
  - containerPort: 443
    hostPort: 9443
    protocol: TCP
