kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: platform
#containerdConfigPatches:
#- |-
#  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5001"]
#    endpoint = ["http://kind-registry:5000"]
nodes:
- role: control-plane
  image: kindest/node:v1.21.14
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  # ingress nginx is exposing hostPort 80 and 443
  - containerPort: 80
    hostPort: 8080
    protocol: TCP
  - containerPort: 443
    hostPort: 8443
    protocol: TCP
  # gitea service is exposing nodePort 31333
  - containerPort: 31333
    hostPort: 8333
    protocol: TCP
