apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- ns.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.1.6/manifests/core-install.yaml
- bootstrap-projects.yaml
- bootstrap-applications.yaml