apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kratix-platform-system
resources:
  - https://raw.githubusercontent.com/syntasso/kratix/main/hack/platform/minio-install.yaml
patchesStrategicMerge:
- |-
  $patch: delete
  apiVersion: v1
  kind: Namespace
  metadata:
    name: kratix-platform-system