apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kratix-platform-system
resources:
  - https://raw.githubusercontent.com/syntasso/kratix/main/distribution/kratix.yaml
  - cluster-worker.yaml
  #- https://raw.githubusercontent.com/syntasso/kratix/main/samples/jenkins/jenkins-promise.yaml