apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitea
resources:
  - https://raw.githubusercontent.com/syntasso/kratix/main/hack/platform/gitea-install.yaml
# `--repository-type=git` makes Kratix use the GitBucketWriter which requires Gitea to be running in the cluster and accessible using specific credentials
# Ref: https://github.com/syntasso/kratix/blob/main/lib/writers/git.go#L40-L50
