apiVersion: v1
kind: Secret
metadata:
  name: gitea-inline-config
  namespace: gitea
stringData:
  server: |-
    APP_DATA_PATH=/data
    DOMAIN=localhost:31333
    ENABLE_PPROF=false
    HTTP_PORT=3000
    PROTOCOL=https
    ROOT_URL=https://0.0.0.0:8333
    SSH_DOMAIN=localhost
    SSH_LISTEN_PORT=22
    SSH_PORT=22

    CERT_FILE=cert.pem
    KEY_FILE=key.pem
