apiVersion: v1
kind: Service
metadata:
  name: gitea-http-lb
  namespace: gitea
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/name: gitea
  type: LoadBalancer
  # must be an IP configured in metallb: kubectl --context kind-platform -n metallb-system get ipaddresspool
  loadBalancerIP: 172.18.255.200