apiVersion: v1
kind: Service
metadata:
  name: gitea-http-lb
  namespace: gitea
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/name: gitea
  type: LoadBalancer