apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - ns.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.5.3/manifests/core-install.yaml
  - bootstrap-projects.yaml
  - bootstrap-argocd.yaml
  - bootstrap-core-services.yaml
patchesStrategicMerge:
  - patch-cm-custom-healthcheck.yaml
  - patch-secret-incluster.yaml
secretGenerator:
  - name: argocd-cluster-in-cluster
    literals:
      - 'config={"tlsClientConfig":{"insecure":false}}'
      - name=in-cluster
      - server=https://kubernetes.default.svc
generatorOptions:
  disableNameSuffixHash: true